"""Read-only pre-director route audit; does not infer routes or replace original gates."""
from pathlib import Path
import argparse, hashlib, json

ROUTES={'image_to_video','native_mg','official_evidence','sourced_chart','vox_layered_broll','real_media','hybrid'}
LIBRARY_ROUTES={'native_mg','official_evidence','sourced_chart','vox_layered_broll'}

def _local(root, value):
    if not isinstance(value,str) or not value.strip():
        raise ValueError('source path must be a non-empty project-relative path')
    rel=Path(value)
    if rel.is_absolute() or '..' in rel.parts:
        raise ValueError('source path must stay inside project')
    path=(root/rel).resolve()
    if not path.is_relative_to(root.resolve()):
        raise ValueError('source symlink escapes project')
    return path

def validate(plan, project, stage='pre-director'):
    errors=[]; warnings=[];root=Path(project)
    if not isinstance(plan,dict):return {'passed':False,'errors':['plan must be an object'],'warnings':[]}
    def required(obj,key,label):
        if not isinstance(obj.get(key),str) or not obj[key].strip(): errors.append(f'{label}: missing {key}')
    def check_source(key,hash_key):
        try:
            path=_local(root,plan.get(key));actual=hashlib.sha256(path.read_bytes()).hexdigest()
            if plan.get(hash_key)!=actual:errors.append(f'{key}: source hash drift or missing hash')
        except (ValueError,OSError) as e:errors.append(f'{key}: {e}')
    check_source('source_script','source_sha256')
    required(plan,'style_intent','plan')
    if stage=='storyboard':
        if plan.get('design_source')!='design.md':errors.append('storyboard must bind this project design.md')
        check_source('design_source','design_sha256')
    segments=plan.get('segments')
    if not isinstance(segments,list) or not segments:
        return {'passed':False,'errors':errors+['segments must be a non-empty list'],'warnings':warnings}
    seen=set()
    for i,s in enumerate(segments):
        label=f'segment {i+1}'
        if not isinstance(s,dict):errors.append(f'{label}: must be object');continue
        for field in ('id','spoken_text','audience_takeaway','reason','visual_action','reading_plan','handoff'):
            required(s,field,label)
        sid=s.get('id')
        if isinstance(sid,str):
            if sid in seen:errors.append(f'{label}: duplicate id')
            seen.add(sid)
        route=s.get('visual_route')
        if not isinstance(route,str) or route not in ROUTES:
            errors.append(f'{label}: unknown visual_route');route=None
        candidates=s.get('library_candidates')
        if not isinstance(candidates,list) or any(not isinstance(v,str) or not v.strip() for v in candidates):
            errors.append(f'{label}: library_candidates must be a string list')
        elif route in LIBRARY_ROUTES and not candidates:
            required(s,'library_skip_reason',label)
        if route=='image_to_video': required(s,'generation_action',label)
        if route=='hybrid':
            required(s,'responsibilities',label)
            if not isinstance(s.get('uses_image_to_video'),bool):errors.append(f'{label}: hybrid must declare uses_image_to_video')
            if s.get('uses_image_to_video') is True:required(s,'generation_action',label)
        exact=s.get('requires_exact_information')
        if not isinstance(exact,bool):errors.append(f'{label}: requires_exact_information must be boolean')
        if route=='image_to_video' and exact:errors.append(f'{label}: exact information cannot be generated by image-to-video')
        evidence=s.get('evidence')
        if not isinstance(evidence,list):errors.append(f'{label}: evidence must be a list');continue
        malformed=any(not isinstance(e,dict) or not isinstance(e.get('ref'),str) or not e['ref'].strip() or not isinstance(e.get('verified'),bool) for e in evidence)
        if malformed:errors.append(f'{label}: malformed evidence entry')
        needs_evidence=exact or route in ('official_evidence','sourced_chart')
        if needs_evidence and (not evidence or malformed or any(e.get('verified') is not True for e in evidence if isinstance(e,dict))):
            msg=f'{label}: exact evidence still requires verification'
            (errors if stage=='storyboard' else warnings).append(msg)
    return {'passed':not errors,'stage':stage,'segments':len(segments),'errors':errors,'warnings':warnings,'boundary':'audit only; no semantic approval, generation, or old-project migration'}

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('command',choices=['validate']);p.add_argument('--project',required=True,type=Path);p.add_argument('--plan',required=True,type=Path);p.add_argument('--stage',choices=['pre-director','storyboard'],default='pre-director');a=p.parse_args()
    try:result=validate(json.loads(a.plan.read_text(encoding='utf-8')),a.project,a.stage)
    except (OSError,UnicodeDecodeError,json.JSONDecodeError) as e:result={'passed':False,'errors':[str(e)]}
    print(json.dumps(result,ensure_ascii=False,indent=2));return 0 if result['passed'] else 1
if __name__=='__main__':raise SystemExit(main())
